#!/usr/bin/env python3

import signal
import sys
import time
import logging

from onion_rf import RFDevice

rfdevice = None

# pylint: disable=unused-argument
def exithandler(signal, frame):
    rfdevice.cleanup()
    sys.exit(0)

logging.basicConfig(level=logging.INFO, datefmt='%Y-%m-%d %H:%M:%S',
                    format='%(asctime)-15s - [%(levelname)s] %(module)s: %(message)s', )


signal.signal(signal.SIGINT, exithandler)
rfdevice = RFDevice(19)
rfdevice.enable_rx()
timestamp = None
logging.info("Listening for codes on GPIO " + str(19))
while True:
    rfdevice.rx_poll_detection()
    if rfdevice.rx_code_timestamp != timestamp:
        timestamp = rfdevice.rx_code_timestamp
        logging.info(str(rfdevice.rx_code) +
                     " [pulselength " + str(rfdevice.rx_pulselength) +
                     ", protocol " + str(rfdevice.rx_proto) + "]")
    time.sleep(0.01)
rfdevice.cleanup()
